services:
  app:
    build: .
    container_name: inventario_app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks: [app-net]

  db:
    image: mysql:8.0
    container_name: inventario_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventario
      MYSQL_ROOT_PASSWORD: CAMBIA_ESTA_ROOT
      MYSQL_USER: inventario
      MYSQL_PASSWORD: CAMBIA_ESTA_PASS
    volumes:
      - dbdata:/var/lib/mysql
    networks: [app-net]

  nginx:
    image: nginx:alpine
    container_name: inventario_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www
    networks: [app-net]
