services:
  app:
    build: .
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "true"
      APP_URL: "https://programin.bid"
      APP_KEY: "base64:dCfN8sKsjoRBcnwY7V7nzTwcsj7UjZYTp3b0Ao25n5I="
      DB_HOST: db
      DB_CONNECTION: mysql
      DB_DATABASE: inventario
      DB_USERNAME: inventario
      DB_PASSWORD: inventario123
    volumes:
      # 1. Compartimos el código de la app en un volumen llamado "web_root"
      - web_root:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: inventario
      MYSQL_USER: inventario
      MYSQL_PASSWORD: inventario123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - dbdata:/var/lib/mysql

  proxy:
    image: nginx:alpine
    restart: always
    expose:
      - "80"
    volumes:
      # 2. Montamos el MISMO volumen aquí para que Nginx vea los archivos
      - web_root:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata:
  web_root: # 3. Definimos el volumen
